version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: pharmacy_user
      POSTGRES_PASSWORD: pharmacy_password
      POSTGRES_DB: pharmacy_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://pharmacy_user:pharmacy_password@db:5432/pharmacy_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
